INSERT INTO  trainers
  (name, gender, age) 
VALUES 
  ('Ash Ketchum', 'male', 10),
  ('Hasty Bogey', 'male', 19),
  ('Audre Harberer', 'female', 10),
  ('Waring Casero', 'male', 26),
  ('Corby Woolforde', 'male', 25),
  ('Shandra Amdtsen', 'female', 21),
  ('Felecia Ridge', 'female', 25),
  ('Jerrie Stockow', 'male', 23),
  ('Toni Darnell', 'female', 16),
  ('Colt Steele', 'male', 26),
  ('Ludwig Wittgenstein', 'male', 18),
  ('Ethelyn Congrave', 'female', 14),
  ('John Howard', 'male', 20),
  ('Shawna Davidson', 'female', 23),
  ('Juan Lopez', 'male', 14),
  ('Mickie Westover', 'male', 17),
  ('Harry Potter', 'male', 12),
  ('Rowan July', 'female', 17),
  ('Way Fryers', 'male', 18),
  ('Caz Noe', 'male', 21),
  ('Rikki Burrage', 'male', 19),
  ('Shea Mollin', 'female', 19),
  ('Lacy Jordan', 'female', 23),
  ('Dale Spencer', 'male', 22),
  ('Izzy Taylor', 'male', 17);
